name: Run tests in vim

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vim_type: ['vim', 'neovim']
        vim_version: ['head', 'stable']
        python_version: [ "3.6.x", "3.7.x", "3.8.x", "3.9.x" ]
        include:
          - vim_type: 'vim'
            vim_version: 'stable'
            vim_vanilla_version: 'v8.0.0000'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python_version }}'

      - name: Setup Vim
        id: vim
        uses: thinca/action-setup-vim@v1
        with:
          gui: no
          vim_type: '${{ matrix.vim_type }}'
          vim_version: '${{ matrix.vim_vanilla_version || matrix.vim_version }}'
          download: always

      - name: Setup environment
        run: |
          echo "EDITOR=${{ steps.vim.outputs.executable }}" >> $GITHUB_ENV

      - name: Setup tests
        run: ./test/setup.sh

      - name: Run tests
        run: ./test/run.sh ./test/testcase_simple_manual
