name: Run tests in vim

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vim_type: ['neovim']
        vim_version: ['head', 'stable']
        python_version: [ "3.5.x", "3.6.x", "3.7.x", "3.8.x", "3.9.x" ]
        include:
          # vim is built against 3.6.x at the moment
          - vim_type: 'vim'
            vim_version: 'head'
            python_version: "3.6.x"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        id: python
        with:
          python-version: ${{ matrix.python_version }}

      - name: Setup Vim
        id: vim
        uses: thinca/action-setup-vim@v1
        with:
          cache: true
          download: always
          gui: false
          vim_type: ${{ matrix.vim_type }}
          vim_version: ${{ matrix.vim_version }}

      - name: Ensure pynvim
        if: ${{ matrix.vim_type == 'neovim' }}
        run: python3 -m pip install --user --upgrade pynvim

      - name: Setup environment
        run: |
          echo "EDITOR=${{ steps.vim.outputs.executable }}" >> $GITHUB_ENV

      - name: Setup tests
        run: ./test/setup.sh

      - name: Run tests
        run: |
          set -euo pipefail
          find test -mindepth 1 -maxdepth 1 -type d -print0 | xargs -0 bash ./test/run.sh
